# Generated by Django 3.0.6 on 2020-06-09 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('users', models.ManyToManyField(db_index=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Name/title of the note. Always unencrypted.')),
                ('json_contents', models.TextField(help_text='Contents of the note in JSON format.', null=True)),
                ('archived', models.BooleanField(default=False, help_text='Has the note been archived?')),
                ('json_metadata', models.TextField(help_text='Note metadata in JSON format.', null=True)),
                ('updated_time', models.BigIntegerField(default=0, help_text='When was note last updated')),
                ('created_time', models.BigIntegerField(default=0, help_text='When was note created')),
                ('repeat_time', models.BigIntegerField(default=0, help_text='When will note be repeated')),
                ('last_repeat_time', models.BigIntegerField(default=0, help_text='When was note last repeated')),
                ('collection', models.ForeignKey(help_text='Collection this note belongs to.', on_delete=django.db.models.deletion.CASCADE, to='mind_palace_main.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='SnoozeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField()),
                ('int_payload', models.IntegerField(null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mind_palace_main.Note')),
            ],
            options={
                'ordering': ['dt'],
            },
        ),
    ]
